## Assessment overview

This course will be assessed on the basis of **2 formative assessments** and **2 summative assessments**.

**Formative assessments** are mock assessments that give you the chance for an interim check in with what you have learnt and what you might need to revise. They will not be individually marked, but a model answer will be shared after the deadline. There will be **two formative assessments**.

You will have to submit **two summative assessments**, each covering all the course content. They will weight 50% and 50% of the final mark.

See below for details (**DETAILS TO BE ADDED**).

## Feedback and marking

The formative assessments will not be individually marked and feedback will consist of a model answer, shared after the formative deadline. You will receive individual feedback for the summative assessments, as comments on the submitted file in Turnitin.

The comments will be categorised according the the Feedback Categorisation Rubric used for this course, which you can see [here](https://uoe-my.sharepoint.com/:x:/g/personal/scoretta_ed_ac_uk/EUCBJX110bREo-JyR1_42egBlT-2xH0XBLjE75kYU4jJJA?e=U99nlT). The rubric is based on the learning outcomes of the course. For each criterion in the rubric there are three possible outcomes: insufficient, developing, proficient. This should help you identify areas of strength and those that can be improved.

Note that the Feedback Categorisation Form is **not used to calculate a numeric mark**. Marking will follow the PPLS MSc Common Marking Scheme, which you can find [here](https://uoe.sharepoint.com/:u:/r/sites/hss/ppls/MScHub/SitePages/Marking-%26-Moderation-Procedure.aspx?csf=1&web=1&e=RyVb39) (login required).

More specifically, we will use a "step marking" procedure, where, within each mark band, you can get a 2, 5 or 8 (for example, 62, 65 or 68). We will not use other numbers within the scale. These are the criteria for getting 2, 5, or 8:

- 2: The criteria for the mark band have been achieved, but there might be minor issues.
- 5: The criteria for the mark band have been achieved fully.
- 8: The criteria for the mark band have been achieved fully and in a particularly remarkable way, but not in such a way to grant a higher mark band.

Finally, please note that *marking does not follow a point-based system*, i.e. different exercises are not assigned a specific amount of points you can obtain and we will instead adopt an "impression-based" marking system, based on the descriptors of the PPLS MSC Common Marking Scheme.

## Formative assessments

::: {.callout-warning}
## Formative 1: Week 5 (Thu 15 February at noon)

**Reading and visualising data**

This formative assessments covers Weeks 1-4.

<!-- You can find the instructions and data for the first formative here: <https://github.com/uoelel/DAL-f1/>. -->
:::

::: {.callout-warning}
## Formative 2: Week 7 (Thu 7 March at noon)

**Data transformation**

This formative assessments covers Weeks 1-6.

<!-- You can find the instructions and data for the second formative here: <https://github.com/uoelel/DAL-f2/>. -->
:::

## Summative assessments

::: {.callout-tip}
## Summative 2 data proposal: Monday 25 March at noon

For the second summative assessment you will have to find a data set from published research of your choice and write a short data analysis report on the chosen data.

**You must submit to Turnitin for approval a brief description of the data set including a link to the relevant publication, by Monday 25th March.**
:::

::: {.callout-tip}
## Summative 1: Week 10 (Thu 28 March at noon)

**Due on Thursday 28 March at noon**

The first summative contains 2 guided exercises that cover things done in Weeks 1 to 7.

You can find the instructions and data for the first summative here: <https://github.com/uoelel/dal-s1>.

:::

::: {.callout-tip}
## Summative 2: Thu 25 April at noon

**Due on Thursday 25 April at noon**

For the second summative assessment you will have to find a data set from published research of your choice and write a short data analysis report on the chosen data.

**You must submit to Turnitin for approval a brief description of the data set including a link to the relevant publication, by Monday 25th March.**

**The summative assessment report is due on 25 April and should include:**

-   A brief explanation of the study the data comes from (remember to include proper attribution by citing relevant publications).
-   A general description of the data frame (number and types of columns, number of observations, summary measures).
-   Plots that illustrate patterns in the data (at least 5). Each plot should be accompanied by a caption and a textual description.
:::
