## Schedule overview

| Week   | Lecture                                                        | Lab                                                    |                                        |
|------------------|-------------------|------------------|------------------|
| 1      | [Quantitative methods and uncertainty](slides/lecture-w01.qmd) | [R basics](tutorials/tutorial-w01.qmd)                 |                                        |
| 2      | [Research process](slides/lecture-w02.qmd)                     | [RStudio + R scripts](tutorials/tutorial-w02.qmd)      |                                        |
| 3      | [File management](slides/lecture-w03.qmd)                      | [Read data](tutorials/tutorial-w03.qmd)                |                                        |
| 4      | [Data viz](slides/lecture-w04.qmd)                             | [Quarto + Plotting basics](tutorials/tutorial-w04.qmd) |                                        |
| 5      | [Statistical variables](slides/lecture-w05.qmd)                | [Data transformation I](tutorials/tutorial-w05.qmd)    | [F1](https://github.com/uoelel/dal-f1) |
| FL     | *No classes*                                                   |                                                        |                                        |
| 6      | [Data summaries](slides/lecture-w06.qmd)                       | [Data transformation II](tutorials/tutorial-w06.qmd)   |                                        |
| 7      | [Tidy data](slides/lecture-w07.qmd)                            | [Data tidying and joining](tutorials/tutorial-w07.qmd)                                           | F2                                     |
| 8      | Plot design                                                    | Advanced plotting                                      |                                        |
| 9      | Troubleshooting                                                | Fixing errors                                          |                                        |
| 25 Mar |                                                                |                                                        | S2 proposal                            |
| 28 Mar |                                                                |                                                        | [S1](https://github.com/uoelel/dal-s1) |
| 25 Apr |                                                                |                                                        | S2                                     |

## Functions and data

|     | Functions                                                                                                          | Data                                                                                                                                                                                                                               |
|------------------|--------------------------|----------------------------|
| 1   | c(), sum(), mean(), cat(), data.frame()                                                                            |                                                                                                                                                                                                                                    |
| 2   | length(), library(), .libPath()                                                                                    |                                                                                                                                                                                                                                    |
| 3   | read_csv(), read_excel(), readRDS()                                                                                | [shallow](https://uoelel.github.io/qm-data/data/song2020/shallow.html), [relatives](https://uoelel.github.io/qm-data/data/los2023/relatives.qmd), [glot_status](https://uoelel.github.io/qm-data/data/coretta2022/glot_status.qmd) |
| 4   | ggplot(), aes(), geom_point(), labs(), colour and alpha, scale_colour_brewer(), scale_colour_viridis_d(), \|\>     | [polite](https://uoelel.github.io/qm-data/data/winter2012/polite.qmd)                                                                                                                                                              |
| 5   | filter(), mutate(), geom_bar(), as.factor(), factor(), facet_grid()                                                | [glot_status](https://uoelel.github.io/qm-data/data/coretta2022/glot_status.qmd), [polite](https://uoelel.github.io/qm-data/data/winter2012/polite.qmd)                                                                            |
| 6   | group_by(), summarise(), count(), geom_density(), geom_rug(), mean(), sd(), median(), min(), max(), range(), log() | [shallow](https://uoelel.github.io/qm-data/data/song2020/shallow.qmd), [gestures](https://uoelel.github.io/qm-data/data/cameron2020/gestures.qmd)                                                                                  |
| 7   | pivot\_\*(), join\_\*(), list.files(), geom_violin(), geom_jitter(), facet_wrap()                                  |                                                                                                                                                                                                                                    |
| 8   | geom_hist(), stat_ellipse(), geom_tile(), likert, geom_sf                                                          |                                                                                                                                                                                                                                    |
| 9   |                                                                                                                    |                                                                                                                                                                                                                                    |
| F1  |                                                                                                                    | [token-measures](https://uoelel.github.io/qm-data/data/coretta2018/token-measures.qmd)                                                                                                                                             |
| F2  |                                                                                                                    |                                                                                                                                                                                                                                    |
| S1  |                                                                                                                    |                                                                                                                                                                                                                                    |
| S2  |                                                                                                                    |                                                                                                                                                                                                                                    |

## Weekly schedule

### Week 1

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What is quantitative data analysis?
-   Is statistics a science, an art, or both?
-   How do uncertainty and variability affect data analysis?

**Skills**

-   Think critically about statistics, uncertainty and variability.
-   Use R to perform simple calculations.
-   Master the basics of the programming language R.
:::

::: {.callout-note collapse="false"}
#### Homework

**Course website**

-   Carefully read the [homepage](index.qmd).

-   Familiarise yourself with this *Course content* page (note that the materials will be updated throughout the course).

**Intake form**

-   **You must complete the intake form before coming to the Tuesday lecture.**
-   The link to the form can be found on the Learn website.

**OPTIONAL: Install R, RStudio and Quarto**

-   The labs will take place in the PPLS computer lab which will have all the necessary software (hopefully...).
-   If instead you wish to use your own laptop, you are welcome to do so provided you take care of installing everything and fix issues that might arise. We won't be able to help you with the installation process.
-   Please, follow the instructions in the [Setup](setup.qmd) page.
:::

::: {.callout-tip collapse="false"}
#### Readings

**ALL READINGS ARE OPTIONAL.** The textbook can be used to revise what done in class and you can pick and choose any of the other readings based on your interests.

**Textbook**

This course will be loosely based on the following online textbook. Note that the order of the contents of the course will not closely follow that of this book, but specific chapter will be noted on this page in each week

-   [R for Data Science](https://r4ds.hadley.nz) (**R4DS**).
-   [The Turing Way](https://the-turing-way.netlify.app/index.html) (**TTW**).

**Other**

-   [Ellis and Levy 2008](https://www.informingscience.org/Publications/438?Source=%2FJournals%2FInformingSciJ%2FArticles%3FVolume%3D11-2008). Framework of Problem-Based Research: A Guide for Novice Researchers on the Development of a Research-Worthy Problem.
-   [Methods as theory](https://stefanocoretta.github.io/posts/2021-03-28-methods-as-theory/).
-   [Vasishth and Gelman 2021](https://doi.org/10.1515/ling-2019-0051). How to embrace variation and accept uncertainty in linguistic and psycholinguistic data analysis.
-   Molnar 2022. Modeling Mindsets: The many cultures of learning from data.
-   [Darwin Holmes 2020](https://doi.org/10.34293/education.v8i4.3232). Researcher Positionality - A Consideration of Its Influence and Place in Qualitative Research - A New Researcher Guide
-   [Jafar 2018](https://doi.org/10.1136/emermed-2017-207158). What is positionality and should it be expressed in quantitative studies?
:::

### Week 2

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   Which are the steps of the research process/cycle?
-   How can questionable research practices affect each step in the research cycle?
-   How can we prevent questionable research practices?

**Skills**

-   Using RStudio and Quarto Projects
-   Write and run code in R scripts.
-   Install and attach R packages.
:::

::: {.callout-tip collapse="false"}
#### Readings

**Textbook**

-   R4DS [Ch 6](https://r4ds.hadley.nz/workflow-scripts).

**From the lecture**

-   [Korback and Roettger 2023](https://doi.org/10.5070/G6011135). Assessing the replication landscape in experimental linguistics.
-   [Kirby and Sonderegger 2018](https://doi.org/10.1016/j.wocn.2018.05.005). Mixed-effects design analysis for experimental phonetics.
-   [Gaeta and Brydges 2020](https://doi.org/10.1044/2020_JSLHR-19-00299). An Examination of Effect Sizes and Statistical Power in Speech, Language, and Hearing Research.
-   [Brysbaert 2020](https://doi.org/10.1017/S1366728920000437). Power considerations in bilingualism research: Time to step up our game.
-   [An estimate of number of speakers per study in phonetics](https://stefanocoretta.github.io/posts/2019-05-03-speakers-per-study/) (Coretta 2019).
-   [Bochynska et al. 2023](https://doi.org/10.5070/G6011239). Reproducible research practices and transparency across linguistics.

**Other**

-   [Study design](https://uoelel.github.io/study-design.html).
-   [Falsifiability](https://uoelel.github.io/extra/falsifiable.html).
:::

### Week 3

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What does file management involve?
-   What is a research compendium?
-   What are licenses and how does one choose how to license work?

**Skills**

-   Organising project files and picking licenses.
-   Read data into R.
-   Submitting a Data Management Plan.
:::

::: {.callout-tip collapse="false"}
#### Readings

**Textbook**

-   R4DS [Ch 6](https://r4ds.hadley.nz/workflow-scripts).

-   TTW, [Research Compendia](https://the-turing-way.netlify.app/reproducible-research/compendia#rr-compendia) and [File naming conventions](https://the-turing-way.netlify.app/project-design/filenaming).

**From the lecture**

-   [UoE Research Data Management policy](https://www.ed.ac.uk/information-services/about/policies-and-regulations/research-data-policy).

-   [UoE DMP online](https://dmponline.ed.ac.uk/).

-   [Creative Commons licenses](https://creativecommons.org/share-your-work/).

**Other**

-   
:::

### Week 4

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What are the principles of good data visualisation?
-   Which are the pitfalls to avoid?
-   How can showing the raw data make the plot more reliable?

**Skills**

-   Create dynamic reports with Quarto.
-   Learn about plotting systems.
-   Basics of plotting with ggplot2.
:::

::: {.callout-tip collapse="false"}
#### Readings

**Textbook**

-   R4DS [Ch 1](https://r4ds.hadley.nz/data-visualize).
-   [Get started with Quarto](https://quarto.org/docs/get-started/hello/rstudio.html).

**From the lecture**

-   [Spiegerhalter 2019](https://www.penguin.co.uk/books/294857/the-art-of-statistics-by-spiegelhalter-david/9780241258767). The art of statistics.

**Other**

-   [Fundamentals of data visualisation](https://clauswilke.com/dataviz/).

**Catalogues**

-   [Directory of visualisations](https://clauswilke.com/dataviz/directory-of-visualizations.html)
-   [Data viz catalogue](https://datavizcatalogue.com/index.html)
-   [Data Viz project](https://datavizproject.com)
-   [Top 50](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
-   [Data Viz](https://datavizm20.classes.andrewheiss.com/)

**Colour**

-   [ColorBrewer2](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3).
-   [MetBrewer](https://github.com/BlakeRMills/MetBrewer).
-   [Use colour wisely](https://albert-rapp.de/post/2022-02-19-ggplot2-color-tips-from-datawrapper/).

**Recommendations**

-   [Same stats different data](https://www.research.autodesk.com/app/uploads/2023/03/same-stats-different-graphs.pdf_rec2hRjLLGgM7Cn2T.pdf).
-   [Behind bars](https://stats.stackexchange.com/a/367889).
-   [I stopped using box plots](https://nightingaledvs.com/ive-stopped-using-box-plots-should-you/).
-   [Issues with error bars](https://www.data-to-viz.com/caveat/error_bar.html).
:::

### Week 5

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What is a statistical variable?
-   Which types of statistical variable are there?
-   What is "operationalisation"?

**Skills**

-   Filter rows and mutate columns.
-   Create bar charts.
-   Separate data in plots using faceting.
:::

### Week 6

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What are summary measures?
-   Which summary measures are appropriate for which type of variable?
-   How should summary measures be reported?

**Skills**

-   Obtain summary measures in R.
-   Use grouped data.
-   Create density plots.
:::

::: {.callout-tip collapse="false"}
#### Readings

**Textbook**

-   R4DS [Ch 3](https://r4ds.hadley.nz/data-transform.html#sec-summarize).
:::

### Week 7

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What types of data do exist?
-   What does data coding entail?
-   What is tidy data and what does it mean for data to be non-tidy?

**Skills**

-   Coding data.
-   Tidy up non-tidy tibbles.
-   Join separate tibbles based on key columns.
:::

::: {.callout-tip collapse="false"}
#### Readings

**Textbook**

-   R4DS [Ch 5](https://r4ds.hadley.nz/data-tidy).
-   R4DS [Ch 19](https://r4ds.hadley.nz/joins).
:::
